.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. farmcoin_qt test_farmcoin_qt
clean: FORCE
	$(MAKE) -C .. farmcoin_qt_clean test_farmcoin_qt_clean
check: FORCE
	$(MAKE) -C .. test_farmcoin_qt_check
farmcoin-qt farmcoin-qt.exe: FORCE
	 $(MAKE) -C .. farmcoin_qt
